### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'commands')

### ISSUE THREAD

**Issue by Bodeyibl** [WilardzySenpai/WaifuMusic#2]
Hi, i just tried your awsome bot but i cant get past this error...
I didnt change anything, i just did the config and i keep getting this error code.

```
TypeError: Cannot read properties of undefined (reading 'commands')
    at loadslashCommands (D:\[Coding]\Desktop\WaifuMusic-master\Handlers\commandHandler.js:51:14)
    at D:\[Coding]\Desktop\WaifuMusic-master\Structures\WaifuMusic.js:80:3
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

Thanks in advance!

**Comment by Hachiiki** [comment]
> Hi, i just tried your awsome bot but i cant get past this error... I didnt change anything, i just did the config and i keep getting this error code.
> 
> ```
> TypeError: Cannot read properties of undefined (reading 'commands')
>     at loadslashCommands (D:\[Coding]\Desktop\WaifuMusic-master\Handlers\commandHandler.js:51:14)
>     at D:\[Coding]\Desktop\WaifuMusic-master\Structures\WaifuMusic.js:80:3
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
> ```
> 
> Thanks in advance!

Hello! In order to ensure proper functionality, please make sure to fill in the `DEV_GUILD` field in your `config.js` file before starting your bot. Once this step is completed, please invite your bot to the specified guild before proceeding to run it. 

Some of the slashComands are set to developers, To make sure everything runs smoothly, please invite the bot to the guild specified in the config.js file. This way, the dev slashCommands will only be deployed to that specific guild. Thanks for your cooperation!
