### ISSUE TITLE
code: 'WebhookTokenUnavailable'

### ISSUE THREAD

**Issue by shishir1337** [WilardzySenpai/WaifuMusic#5]
```
[AntiCrash] | [UnhandledRejection_Logs] | [start] : ===============
Error [WebhookTokenUnavailable]: This action requires a webhook token, but none is available.
    at WebhookClient.send (C:\Users\SHISHIR1337\Documents\bot\WaifuMusic\node_modules\discord.js\src\structures\Webhook.js:206:28)
    at process.<anonymous> (C:\Users\SHISHIR1337\Documents\bot\WaifuMusic\Handlers\errorHandler.js:30:13)
    at process.emit (node:events:513:28)
    at emit (node:internal/process/promises:149:20)
    at processPromiseRejections (node:internal/process/promises:283:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:32) {
  code: 'WebhookTokenUnavailable'
}
[AntiCrash] | [UnhandledRejection_Logs] | [end] : ===============
```

**Comment by gabrieldiaspereira** [comment]
Could you tell us how you managed to solve the problem?
@shishir1337 @WilardzySenpai

**Comment by Hachiiki** [comment]
> Could you tell us how you managed to solve the problem?
> @shishir1337 @WilardzySenpai 

go to the config folder and then find the webhook json file there you'll be able to change or put the value needed.

**Comment by gabrieldiaspereira** [comment]
> > Could you tell us how you managed to solve the problem?
> > @shishir1337 @WilardzySenpai
> 
> go to the config folder and then find the webhook json file there you'll be able to change or put the value needed.

Thanks!
